language: go
go:
  - 1.4
  - 1.5
  - tip

install:
  - go get github.com/go-ini/ini
  - go get github.com/jmespath/go-jmespath
  - go get github.com/aws/aws-sdk-go
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: go test -v ./...
